openapi: 3.0.3
info:
  title: MH-API
  version: 1.0.0
servers:
  - url: https://mh-api-v2-8aznfogc.an.gateway.dev/
    description: PROD環境
paths:
  /v1/health:
    get:
      summary: ヘルスチェックエンドポイント
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                status: OK
  /v1/monsters:
    get:
      summary: 全てのモンスター情報を取得する
      responses:
        "200":
          description: モンスター情報の取得に成功
          content:
            application/json:
              example:
                Monsters:
                  - id: 1
                    name: ジンオウガ
                    desc: 別名雷狼竜とよばれる電気を操る牙竜種
                    location: 渓流
                    specify: 牙竜種
                    weakness_attack: 頭部
                    weakness_element: 氷
                  - id: 2
                    name: タマミツネ
                    desc: 別名泡狐竜と呼ばれる泡状の液体を操る海竜種
                    location: 渓流
                    specify: 泡狐竜
                    weakness_attack: 頭部
                    weakness_element: 火
        "404":
          description: モンスターが見つかりません
          content:
            application/json:
              example:
                message: Not Found
    post:
      summary: モンスターの情報を追加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                desc:
                  type: string
                location:
                  type: string
                specify:
                  type: string
                weakness_attack:
                  type: string
                weakness_element:
                  type: string
            example:
              name: ジンオウガ
              desc: 別名雷狼竜とよばれる電気を操る牙竜種
              location: 渓流
              specify: 牙竜種
              weakness_attack: 頭部
              weakness_element: 氷
      responses:
        "200":
          description: モンスターの情報の登録に成功
          content:
            application/json:
              example:
                message: success

        "403":
          description: 認証失敗
          content:
            application/json:
              example:
                message: Authentication error

        "500":
          description: サーバエラーにより更新失敗
          content:
            application/json:
              example:
                message: Internal Server Error
  /v1/monsters/{id}:
    get:
      summary: モンスター情報を取得する
      parameters:
        - $ref: "#/components/parameters/PathId"
      responses:
        "200":
          description: モンスター情報の取得に成功
          content:
            application/json:
              example:
                name: ジンオウガ
                desc: 別名雷狼竜とよばれる電気を操る牙竜種
                location: 渓流
                specify: 牙竜種
                weakness_attack: 頭部
                weakness_element: 氷
        "404":
          description: モンスターの情報が見つかりません
          content:
            application/json:
              example:
                message: Not Found
  /v1/monsters/json:
    post:
      summary: jsonを使用してモンスターの情報一括追加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                desc:
                  type: string
                location:
                  type: string
                specify:
                  type: string
                weakness_attack:
                  type: string
                weakness_element:
                  type: string
            example:
              req:
                - name: ジンオウガ
                  desc: 別名雷狼竜とよばれる電気を操る牙竜種
                  location: 渓流
                  specify: 牙竜種
                  weakness_attack: 頭部
                  weakness_element: 氷
      responses:
        "200":
          description: モンスターの情報の登録に成功
          content:
            application/json:
              example:
                message: success
        "403":
          description: 認証失敗
          content:
            application/json:
              example:
                message: Authentication error
        "500":
          description: サーバエラーによ登録失敗
          content:
            application/json:
              example:
                message: Internal Server Error
  /v1/monsters/{updateid}:
    patch:
      summary: モンスターの情報を更新する
      parameters:
        - $ref: "#/components/parameters/PathId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                desc:
                  type: string
                location:
                  type: string
                specify:
                  type: string
                weakness_attack:
                  type: string
                weakness_element:
                  type: string
            example:
              name: ジンオウガ
              desc: 別名雷狼竜とよばれる電気を操る牙竜種
              location: 渓流
              specify: 牙竜種
              weakness_attack: 頭部
              weakness_element: 氷
      responses:
        "200":
          description: モンスターの情報の更新に成功
          content:
            application/json:
              example:
                message: success
        "403":
          description: 認証失敗
          content:
            application/json:
              example:
                meesage: Authentication error
        "500":
          description: サーバエラーにより更新失敗
          content:
            application/json:
              example:
                message: Internal Server Errorr
  /v1/monsters/{deleteid}:
    get:
      summary: モンスターの情報を削除する
      parameters:
        - $ref: "#/components/parameters/PathId"
      responses:
        "200":
          description: モンスターの情報の削除に成功
          content:
            application/json:
              example:
                message: success
        "403":
          description: 認証失敗
          content:
            application/json:
              example:
                message: Authentication error
        "500":
          description: サーバエラーにより削除失敗
          content:
            application/json:
              example:
                message: Internal Server Error
components:
  parameters:
    PathId:
      name: id
      in: path
      description: モンスターのID
      required: true
      schema:
        type: string

  requestBodies:
    Monster:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              desc:
                type: string
              location:
                type: string
              specify:
                type: string
              weakness_attack:
                type: string
              weakness_element:
                type: string

  schemas:
    Monster:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        desc:
          type: string
        location:
          type: string
        specify:
          type: string
        weakness_attack:
          type: string
        weakness_element:
          type: string

    Monsters:
      type: array
      properties:
        id:
          type: integer
        name:
          type: string
        desc:
          type: string
        location:
          type: string
        specify:
          type: string
        weakness_attack:
          type: string
        weakness_element:
          type: string
    message:
      type: string
